# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up build environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: mvn -B install --file pom.xml

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2

      - name: Upload JaCoCo badge
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Ruben Boada'
            git config --global user.email 'rubenboadana@gmail.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v2
        with:
          name: Jacoco report
          path: target/site/jacoco/

      - name: Check dependency vulnerabilities
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: '${artifactId}'
          path: '.'
          format: 'HTML'
          args: >
            --enableRetired
      - name: Upload vulnerabilities report
        uses: actions/upload-artifact@v2
        with:
          name: Dependency vulnerabilities report
          path: ${{github.workspace}}/reports
